version: "3.2"

services:
   redis:
      image: redis
      ports:
         - "6379:6379"

   postgres:
      image: postgres
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=fowl
         - POSTGRES_PASSWORD=fowl
      ports:
         - 5432:5432
      volumes:
         - ./databases/postgres:/var/lib/postgresql/data/
